"use strict";
let miNumero = 10;
miNumero = 10 + 10;
miNumero = 2.5;
console.log(miNumero);
let booleano = true;
booleano = false;
//booleano = 3;
//booleano = null;
let encendido;
//console.log(encendido);
encendido = true;
console.log('Encendido es:', encendido);
console.log('Encendido es:', { encendido });
encendido = true && false;
encendido = true && true;
encendido = false && true;
encendido = false && false;
console.log('Resultado:', encendido);
let normal = 'hola';
normal = 10;
normal = true;
normal = 11.25;
console.log('Normal:', normal);
